theme: jekyll-theme-time-machine
 wwbody: | <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
 wwbody: | <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
 wwbody: | <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
 wwbody: | <link rel="manifest" href="/site.webmanifest">
 wwbody: | <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
 wwbody: | <meta name="msapplication-TileColor" content="#da532c">
 wwbody: | <meta name="theme-color" content="#ffffff">
